### ISSUE TITLE
Fail if `--scan` or publishAlways() is set and the user is not authenticated

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle-enterprise-conventions-plugin#1]
I just saw that when trying to publish a build scan from `gradle/gradle`, that no build scan has been published even though I requested `--scan`. I suppose this is due to the convention plugin overriding to `publishIfAuthenticated()`. I actually want to get an error message telling me to either
- authenticate (describing how), or
- use a different server for publishing the build scan

I think that would be good for CI and local builds.

**Comment by blindpirate** [comment]
@wolfs I guess you need to configure `ge.gradle.org=<<AccessToken>>` in your `~/.gradle/enterprise/keys.properties`. But your suggestion is a good idea.

@etiennestuder WDYT? My understanding is:

- If `publishAlways` is enabled and user is not authenticated, there will be an error.
- If `publishIfAuthenticated` is enabled, users might be confused when they request `--scan` but get nothing. 

Which do you think should be the default behavior of this plugin?

**Comment by blindpirate** [comment]
I enabled `publishAlways` in this plugin: https://github.com/gradle/gradle-enterprise-conventions-plugin/blob/master/src/main/java/com/gradle/enterprise/conventions/GradleEnterpriseConventionsPlugin.java#L69

You can try `0.3` version.

**Comment by etiennestuder** [comment]
> @etiennestuder WDYT? My understanding is:
> 
> * If `publishAlways` is enabled and user is not authenticated, there will be an error.
> * If `publishIfAuthenticated` is enabled, users might be confused when they request `--scan` but get nothing.

`publishIfAuthenticated` serves as a gate to only publish if publishing is enabled (--scan, publishAlways, etc.) AND an access token for the given GE instance is present on the build's machine. In case these two conditions are not both fulfilled, no build scan is published silently.

Note this is an internal API, exactly for the reasons you are seeing: it is not obvious what the actual behavior is.

**Comment by blindpirate** [comment]
Thanks @etiennestuder , this is done in `0.3` release.

**Comment by etiennestuder** [comment]
Cool, @blindpirate.
